#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
for nb in 1st_stage.ipynb 2nd_stage.ipynb; do
  jupyter nbconvert \
    --to html \
    --execute "$nb" \
    --ExecutePreprocessor.allow_errors=True \
    --ExecutePreprocessor.timeout=-1 \
    --FilesWriter.build_directory=../results
done

